### ISSUE TITLE
js not works for firefox, just works for IE

### ISSUE THREAD

**Issue by aleitech** [xuxiaodong/using-cli#1]
i can not explore in firefox page by page

**Comment by xuxiaodong** [comment]
Please try out the following command:

```
firefox -safe-mode
```

Or, If you using Vimperator/Pentadactyl add-on, please press `Ctrl + z`。

**Comment by aleitech** [comment]
It works, after I pressed Esc + Shift, because I am using Vimperator.
thank you!

**Comment by xuxiaodong** [comment]
You're welcome :)
